### ISSUE TITLE
Model and apply Metacontrol to the system

### ISSUE THREAD

**Issue by Rezenders** [kas-lab/pipeline_inspection#11]
First task is to decide which adaptations we are going to apply. After that, we need to model it with metacontrol and actually apply it.

**Comment by Rezenders** [comment]
system modes config file for the pilot example: https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/master/metacontroller_pilot/modes_conf/pilot_modes.yaml

**Comment by Rezenders** [comment]
lifecyclenodes: https://github.com/ros2/demos/blob/foxy/lifecycle/README.rst

**Comment by jeroenzwan** [comment]
More information on the system_modes: https://github.com/micro-ROS/system_modes/blob/master/system_modes/README.md#how-to-apply

**Comment by EGAlberts** [comment]
https://github.com/MROS-RobMoSys-ITP/mros_navigation2/tree/master/nav2_bt_navigator/behavior_trees

**Comment by jeroenzwan** [comment]
Mode Change server is declared here: https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/master/metacontroller_pilot/metacontroller_pilot/simple_mode_manager.py

**Comment by Rezenders** [comment]
The correct system_modes file is this one: https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/master/pilot_urjc_bringup/params/pilot_modes.yaml

**Comment by Rezenders** [comment]
Modeling is done, we just need to round up the details to apply it.

**Comment by Rezenders** [comment]
I am closing this, as we are now able to apply the search adaptation, and switch between tasks. It is still missing to add thruster adaptation, but there are other issues for this point.
