### ISSUE TITLE
Is the spiral search adaptation supposed to change altitude or spiral width?

### ISSUE THREAD

**Issue by Rezenders** [kas-lab/pipeline_inspection#59]
Is the spiral search adaptation supposed to change altitude or spiral width?
If I remember correctly, @jeroenzwan @JulianePa and I agreed on adapting the altitude of the search. 
However, now the spiral width is what is being adapted.

To change the search altitude, the new `BlueROVGazebo` class can be used.

**Comment by JulianePa** [comment]
Yes, we agreed on changing the altitude of the search.
